/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_citius_bwa_BwaJni */

#ifndef _Included_es_citius_bwa_BwaJni
#define _Included_es_citius_bwa_BwaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_citius_bwa_BwaJni
 * Method:    bwa_jni
 * Signature: (I[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_es_citius_bwa_BwaJni_bwa_1jni
  (JNIEnv *, jobject, jint, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
